### ISSUE TITLE
Breaking changes between v1.0.0 and v1.1.0

### ISSUE THREAD

**Issue by stevebauman** [Gioni06/GPT3Tokenizer#4]
Hi there!

I was wondering if we should expect breaking changes in minor version releases (`major.minor.patch`)?

For example, the `encode` method can no longer be called statically, and throws a PHP exception when attempting to do so:

v1.0.0:
https://github.com/Gioni06/GPT3Tokenizer/blob/4010fd458ff33d5b23e3cffd5195c77a609321ec/src/Gpt3Tokenizer.php#L148

v1.1.0:
https://github.com/Gioni06/GPT3Tokenizer/blob/2070dc49c02eef9a856486502c00db067116f39d/src/Gpt3Tokenizer.php#L196

Wanted to check on your versioning scheme so I can adjust my composer config accordingly, as these v1.1 changes have broken my tests.

Thanks for your time and this package! ❤️

**Comment by Gioni06** [comment]
@stevebauman
I apologize for any inconvenience caused by the recent changes I made without prior notice. 
In the future I will stick to semantic versioning. It was basically a mistake I made at the beginning of the development and I hoped to get away with it as long as nobody but me uses the package :)

Thanks for your feedback!

**Comment by Gioni06** [comment]
Here's a bit of background on the changes: 
I noticed that the encode and decode performance was not sufficient for my use case, so I made some internal optimizations that improved the performance dramatically. The consequence of this was that the API changed. So if you make the necessary changes in your code, you should notice improvements from several seconds to milliseconds.

**Comment by stevebauman** [comment]
@Gioni06 Oh that's okay! No worries at all, just wanted to see if you were using semantic versioning or not so I could target properly.

Thanks so much for your work on this! ❤️ 

Also that's excellent news about the performance gains, nice work! 👍
